# Generated by Django 4.0.2 on 2022-02-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
