# Generated by Django 4.0.2 on 2022-03-02 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_id',
        ),
    ]
